language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
    - libboost-filesystem-dev
    - libboost-system-dev
    - libboost-test-dev

before_script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_CXX_COMPILER=g++-4.8 ..

script: make

os: linux