language: cpp

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8

before_script:
    - mkdir build
    - cd build
    - cmake ..

script: make

os:
	- linux

